dtype = floor(data/100);
dspec = mod(data,100);

aspec = mod(rawalg,10);
alg = floor(rawalg/10);
%          % (1)      (2)       (3)       (4)      (5)       (6)
% spec = {'rvOne', 'rv0595', 'rv1090', 'rv2080', 'rv5050','rv8020', ...
%         '0199','0397','0595','1090','1585','2080','5050','8020', '9010'};
%         % (7)    (8)   (9)    (10)   (11)   (12)   (13)   (14)    (15)
        
         % (1)    (2)    (3)     (4)      (5) 
spec = {'0150', '0550', '1050', '2550', '5050'};
randwalk = {1,5,10,20,3};
if aspec==0
    rid = 0;
else
    rid = randwalk(aspec);
end
%%
if dtype==1,
    params = struct(...
        'warmstart',0,...
        'neg_noise_net', 5, ...
        'neg_noise_rat', 5,...
        'isNormed', 1,...
        'isDeep', 1, ...
        'earlystop', 1e-7,...
        'alpha', 0.1, ...
        'mc_run', 1, ...
        'numwalks', rid, ...
        'coldstart', 1, ...
        'coldid', spec(dspec) , ...
        'maxepoch', 1000, ...
        'maxepochctr', 100, ...
        'minepochctr', 1, ...
        'urelax', 0, ...
        'sample', sp, ...
        'data', 'lastfm', ...
        'topM', 200, ...
        'pretrain', 0, ...
        'pretrainiters',500, ...
        'ctr_ratio', 1, ...
        'lv', 100, ...
        'lu', 0.01, ...
        'ln', 0.01, ...
        'lq', 0.1, ...
        'ls', 0.01, ...
        'decay', 1e-3, ...1e-3 for old
        'momentum', 1e-1, ...
        'mid_momentum', 0.5,...
        'max_momentum', 0.8,...
        'nV', 17632, ...
        'nU', 1892, ...
        'nT', 9749,...
        'nF', 100);
    
    para_V = struct(...
        'adagrad', 0, ...
        'bindata', 1, ...
        'actvis', 0, ... 
        'lrate', 1e-3, ...
        'layers', [params.nT params.nF], ...
        'momentum', params.momentum, ...
        'decay', params.decay, ...
        'batchsize', 500, ...
        'nsamples', params.nV, ...
        'noise', 0, ... % visible noise added
        'dropout', 0.1);
    
    para_U = struct(...
        'adagrad', params.warmstart, ...
        'bindata', 0, ...
        'actvis', 1, ... % 4: for tanh-relu
        'lrate', 3e-3, ...
        'layers', [params.nU 500 params.nF], ...
        'momentum', params.momentum, ...
        'nsamples', params.nU, ...
        'decay', params.decay, ...
        'batchsize', 100, ...
        'noise', 0, ... % visible noise added
        'dropout', 0.1);
    
    para_C = struct(...
        'adagrad', 1, ...
        'bindata', 0, ...
        'actvis', 0, ... 
        'lrate', 3e-2, ...
        'layers', [(params.nU + params.nV) params.nF], ... 1000
        'momentum', params.momentum, ...
        'nsamples', params.nU, ...
        'decay', params.decay, ...
        'batchsize', 100, ...
        'noise', 0, ... % visible noise added
        'dropout', 0);
%%
elseif dtype==2,
    params = struct(...
        'warmstart',1,...
        'neg_noise_net', 10, ...
        'neg_noise_rat', 10,...
        'isNormed', 1,...
        'isDeep', 0, ...
        'earlystop', 1e-7,...
        'mc_run', 0, ...
        'numwalks', rid, ...
        'coldstart', 1, ...
        'coldid', sprintf('sp%d/%s',sp,char(spec(dspec))) , ...
        'maxepoch', 300, ...
        'maxepochctr', 100, ...
        'minepochctr', 1, ...
        'urelax', 0, ...
        'sample', sp, ...
        'data', 'delicious', ...
        'topM', 200, ...
        'pretrain', 0, ...
        'pretrainiters',500, ...
        'ctr_ratio', 1, ...
        'lv', 0.01, ...
        'lu', 0.01, ...
        'ln', 0.1, ...
        'lq', 0.1, ...
        'ls', 0.01, ...
        'decay', 1e-3, ...
        'momentum', 1e-1, ...
        'mid_momentum', 0.5,...
        'max_momentum', 0.8,...
        'nV', 69223, ...
        'nU', 1867, ...
        'nT', 40897, ...
        'nF', 200);
    
    para_V = struct(...
        'adagrad', 0, ...
        'bindata', 1, ...
        'actvis', 0, ... 
        'lrate', 3e-3, ...
        'layers', [params.nT params.nF], ...
        'momentum', params.momentum, ...
        'decay', params.decay, ...
        'batchsize', 100, ...
        'nsamples', params.nV, ...
        'noise', 0, ... % visible noise added
        'dropout', 0.1);
    
    para_U = struct(...
        'adagrad', params.warmstart, ...
        'bindata', 0, ...
        'actvis', 0, ...
        'lrate', 3e-3, ...
        'layers', [params.nU params.nF], ...
        'momentum', params.momentum, ...
        'nsamples', params.nU, ...
        'decay', params.decay, ...
        'batchsize', 100, ...
        'noise', 0, ... % visible noise added
        'dropout', 0.1);
    
    para_C = struct(...
        'adagrad', 1, ...
        'bindata', 1, ...
        'actvis', 0, ... 
        'lrate', 1e-3, ...
        'layers', [(params.nU + params.nV) params.nF], ... 
        'momentum', params.momentum, ...
        'nsamples', params.nU, ...
        'decay', params.decay, ...
        'batchsize', 100, ...
        'noise', 0, ... % visible noise added
        'dropout', 0.1);
%%
% elseif dtype==3,
%     params = struct(...
%         'warmstart',1,...
%         'isNormed', 1,...
%         'isDeep', 0, ...
%         'earlystop', 1e-7,...
%         'mc_run', 0, ...
%         'numwalks', 10, ...
%         'coldstart', 1, ...
%         'coldid', spec(dspec) , ...
%         'maxepoch', 300, ...
%         'maxepochctr', 300, ...
%         'minepochctr', 1, ...
%         'urelax', 0, ...
%         'maxsample', 1, ...
%         'data', 'livejournal', ...
%         'topM', 200, ...
%         'pretrain', 0, ...
%         'pretrainiters',500, ...
%         'ctr_ratio', 1, ...
%         'lv', 0.01, ...
%         'lu', 0.01, ...
%         'ln', 1, ...
%         'lq', 0.1, ...
%         'ls', 0.01, ...
%         'decay', 1e-3, ...
%         'momentum', 1e-1, ...
%         'mid_momentum', 0.5,...
%         'max_momentum', 0.8,...
%         'nV', 78760, ... 
%         'nU', 17496, ... 
%         'nT', 67597, ... 
%         'nF', 200);
%     
%     para_V = struct(...
%         'adagrad', 0, ...
%         'bindata', 1, ...
%         'actvis', 0, ... 
%         'lrate', 1e-3, ...
%         'layers', [params.nT params.nF], ...
%         'momentum', params.momentum, ...
%         'decay', params.decay, ...
%         'batchsize', 100, ...
%         'nsamples', params.nV, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.01);
%     
%     para_U = struct(...
%         'adagrad', 1, ...
%         'bindata', 0, ...
%         'actvis', 0, ...
%         'lrate', 3e-3, ...
%         'layers', [params.nU params.nF], ...
%         'momentum', params.momentum, ...
%         'nsamples', params.nU, ...
%         'decay', params.decay, ...
%         'batchsize', 500, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.1);
% %%
% elseif dtype==4,
%     params = struct(...
%         'warmstart',0,...
%         'isNormed', 1,...
%         'isDeep', 1, ...
%         'earlystop', 1e-7,...
%         'mc_run', 0, ...
%         'numwalks', 10, ...
%         'coldstart', 1, ...
%         'coldid', spec(dspec) , ...
%         'maxepoch', 500, ...
%         'maxepochctr', 500, ...
%         'minepochctr', 1, ...
%         'urelax', 0, ...
%         'maxsample', 1, ...
%         'data', 'livejournal_activ1', ...
%         'topM', 200, ...
%         'pretrain', 0, ...
%         'pretrainiters',500, ...
%         'ctr_ratio', 1, ...
%         'lv', 0.01, ...
%         'lu', 0.01, ...
%         'ln', 0.005, ...
%         'lq', 0.01, ...
%         'ls', 0.01, ...
%         'decay', 1e-3, ...
%         'momentum', 1e-1, ...
%         'mid_momentum', 0.5,...
%         'max_momentum', 0.8,...
%         'nV', 70387, ... 
%         'nU', 12451, ... 
%         'nT', 67596, ... 
%         'nF', 200);
%     
%     para_V = struct(...
%         'adagrad', 0, ...
%         'bindata', 1, ...
%         'actvis', 0, ... 
%         'lrate', 1e-3, ...
%         'layers', [params.nT params.nF], ...
%         'momentum', params.momentum, ...
%         'decay', params.decay, ...
%         'batchsize', 100, ...
%         'nsamples', params.nV, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.01);
%     
%     para_U = struct(...
%         'adagrad', 0, ...
%         'bindata', 0, ...
%         'actvis', 0, ...
%         'lrate', 3e-3, ...
%         'layers', [params.nU 3000 800 params.nF], ...
%         'momentum', params.momentum, ...
%         'nsamples', params.nU, ...
%         'decay', params.decay, ...
%         'batchsize', 500, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.1);
% %%
% elseif dtype==5,
%     params = struct(...
%         'warmstart',1,...
%         'isNormed', 1,...
%         'isDeep', 0, ...
%         'earlystop', 1e-7,...
%         'mc_run', 0, ...
%         'numwalks', 10, ...
%         'coldstart', 1, ...
%         'coldid', spec(dspec) , ...
%         'maxepoch', 300, ...
%         'maxepochctr', 300, ...
%         'minepochctr', 1, ...
%         'urelax', 0, ...
%         'maxsample', 1, ...
%         'data', 'livejournal_activ10', ...
%         'topM', 200, ...
%         'pretrain', 0, ...
%         'pretrainiters',500, ...
%         'ctr_ratio', 1, ...
%         'lv', 0.01, ...
%         'lu', 0.01, ...
%         'ln', 0.01, ...
%         'lq', 0.01, ...
%         'ls', 0.01, ...
%         'decay', 1e-3, ...
%         'momentum', 1e-1, ...
%         'mid_momentum', 0.5,...
%         'max_momentum', 0.8,...
%         'nV', 40580, ... 
%         'nU', 1024, ... 
%         'nT', 67670, ... 
%         'nF', 200);
%     
%     para_V = struct(...
%         'adagrad', 0, ...
%         'bindata', 1, ...
%         'actvis', 0, ... 
%         'lrate', 1e-3, ...
%         'layers', [params.nT params.nF], ...
%         'momentum', params.momentum, ...
%         'decay', params.decay, ...
%         'batchsize', 100, ...
%         'nsamples', params.nV, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.01);
%     
%     para_U = struct(...
%         'adagrad', 1, ...
%         'bindata', 0, ...
%         'actvis', 0, ...
%         'lrate', 3e-3, ...
%         'layers', [params.nU params.nF], ...
%         'momentum', params.momentum, ...
%         'nsamples', params.nU, ...
%         'decay', params.decay, ...
%         'batchsize', 100, ...
%         'noise', 0, ... % visible noise added
%         'dropout', 0.1);
end;
params.gsl_lib = '/usr/local/lib';
% params.gsl_lib = '../gsldump/lib';
fprintf(1, 'Init data [Dtype: %s - Dspec: %s]\n', params.data, params.coldid);


