maxepoch=1;
segepoch=1;
MOMENTHRES = 0;

params = struct(...
    'topM', 100, ...
    'data', 'livejournal_activ10', ...
    'buff', 100, ...
    'kcd', 10, ...
    'kmf', 15, ...
    'reg_h', .2, ...
    'reg_n', .5, ...
    'dbm_softmaxused', 0, ...
    'datamode', '2D', ...
    'numdim', 40580, ...
    'numtag', 67670, ...
    'numbatches', 19, ...
    'numhid', 100, ... % numhid for RBM model
    'numnet', 1024, ... % old = 1892; new = 50
    'invsig_a', 1/.01, ...% 1/sigma_a
    'invsig_b', 1/.1, ...
    'Epsilonw', 0.01, ...   % Learning rate for weights
    'Epsilonvb', 0.01, ...   % Learning rate for biases of visible units
    'Epsilonhb', 0.01, ...   % Learning rate for biases of hidden units
    'Epsilongr', 0.01, ...
    'Weightcost', 0.001, ...
    'Initialmomentum', 0.2, ...
    'Finalmomentum', 0.8, ...
    'Gamma', 0.9, ...
    'warmrate', -1);

% params = struct(...
%     'topM', 100, ...
%     'data', 'livejournal_activ1', ...
%     'buff', 500, ...
%     'kcd', 10, ...
%     'kmf', 15, ...
%     'reg_h', .2, ...
%     'reg_n', .5, ...
%     'dbm_softmaxused', 0, ...
%     'datamode', '2D', ...
%     'numdim', 70387, ...
%     'numtag', 67596, ...
%     'numhid', 100, ... % numhid for RBM model
%     'numnet', 12451, ... % old = 1892; new = 50
%     'invsig_a', 1/.01, ...% 1/sigma_a
%     'invsig_b', 1/.1, ...
%     'Epsilonw', 0.01, ...   % Learning rate for weights
%     'Epsilonvb', 0.01, ...   % Learning rate for biases of visible units
%     'Epsilonhb', 0.01, ...   % Learning rate for biases of hidden units
%     'Epsilongr', 0.01, ...
%     'Weightcost', 0.001, ...
%     'Initialmomentum', 0.2, ...
%     'Finalmomentum', 0.8, ...
%     'Gamma', 0.9, ...
%     'warmrate', -1);

